config/routes.rb
Testtube::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :welcome, :only => [:index]
  resources :projects, :only => [:index, :show, :update, :destroy, :create] do
    member do
      post :save
    end

    resources :project_models, :only => [:index, :show], :shallow => true
    resources :project_users, :only => [:create, :update, :destroy], :shallow => true
    resources :story_types, :only => [:index, :show, :create, :edit, :update, :new, :destroy]
    resources :user_stories, :only => [:index, :show, :create, :edit, :update, :new, :destroy] do
      member do
        post :save
      end
    end

  end
  root :to => 'welcome#index'

end

app/models/user_story.rb
class UserStory < ActiveRecord::Base
  belongs_to :project
  belongs_to :actor \
    , :foreign_key => "actor_id"
  belongs_to :story_type
  belongs_to :parent_user_story \
    , :class_name => "UserStory" \
    , :foreign_key => "parent_user_story_id"
  has_many :child_user_stories \
    , :class_name => "UserStory" \
    , :foreign_key => "parent_user_story_id" \
    , :dependent => :delete_all
    
  has_many :notes, :as => :notable
  accepts_nested_attributes_for :notes
  
  has_many :story_notes, :dependent => :destroy, :foreign_key => "user_story_id"
  attr_accessible :doit_loe_hours,
    :doit_loe_hours_calculated,
    :fibonacci_estimate,
    :is_estimate_final,
    :is_fully_recorded,
    :priority,
    :so_i_can,
    :want_to,
    :project_id,
    :actor_id,
    :story_type_id,
    :parent_user_story_id,
    :actor_name,
    :stack_rank,
    :notes_attributes

  attr_accessor :actor_name
  
  validates :want_to, 
    :uniqueness => {:message => "the want to clause must be unique", :scope => :project_id}
  validates :want_to, :presence => true
  validates :project_id, :presence => true
  validates :actor_id, :presence => true

  # by default, sort by project, parent_user_story, stack_rank, priority, and id
  default_scope order('project_id, parent_user_story_id, stack_rank, priority, id')

  def actor_name
    actor.actor_singular_name if !actor.nil?
  end
end

app/controllers/user_stories_controller.rb
class UserStoriesController < ApplicationController
  load_and_authorize_resource :project
  load_and_authorize_resource :user_story, :through => :project, :shallow => true

  # before_filter :find_project

  def show
  end
  
  def new
    # need the list of actors to include in the story
    # editor combo box
    @all_actors = get_actors

    @user_story = @project.user_stories.new
    @story_note = @user_story.notes.build

    if params[:parent].present?
      #requesting to add a child of a parent.  set the parent id to the specified
      #parent, and set the stack rank to the the lowest number (highest priority) minus 10
      @user_story.parent_user_story = @project.user_stories.find(params[:parent])
      oldest_child = @user_story.parent_user_story.child_user_stories.first()
      @user_story.stack_rank = oldest_child.nil? ? 10 : oldest_child.stack_rank - 10
    elsif params["after"].present?
      #requesting to add an element after another element.
      #set the parent to the parent of the requested sibling, and the stack rank to the 
      #siblings rank + 1
      bigbro = @project.user_stories.find(params[:after])
      @user_story.parent_user_story = bigbro.parent_user_story
      @user_story.stack_rank = (bigbro.stack_rank || 0)  + 1
    else
      #not sure where we are adding it. 
    end

    puts "*************creating new form: " + params.inspect
    respond_to do |format|
      format.html { render :nothing => true }
      format.js 
    end
  end

  def destroy

    @user_story_id = @user_story.id
    @user_story.delete

    respond_to do |format|
      format.html { render :nothing => true }
      format.js 
    end
  end

  def edit
    # need the list of actors to include in the story
    # editor combo box
    @all_actors = get_actors

    @user_story = @project.user_stories.find(params[:id])
    @story_note = @user_story.notes.build
  
    respond_to do |format|
      format.html { render :nothing => true }
      format.js 
    end
  end

  def index
    # identify which drawers should be in the chest
    @slider_drawers = build_drawers

    # need the list of actors to include in the story
    # editor combo box
    @all_actors = get_actors


    # fetch the root user stories from the DB that are the roots
    # They will contain the rest of the stories recursively
    @root_user_stories = get_root_user_stories

    @user_story = @project.user_stories.new

    puts "***********new user story: " + @user_story.inspect
  end

  def update
    puts "++++++ in update: " + params.inspect
    @user_story = @project.user_stories.find(params[:id])
    @special_action = params[:special_action]

    if @special_action == "parent_change"
      # for the parent change action, insert the story as the first child of the dropped story
      @new_parent_id = params[:new_parent]
      if @new_parent_id.nil?
        @user_story.parent_user_story = nil
        current_first_story = @project.user_stories.where("parent_user_story_id is null").first
      else
        @user_story.parent_user_story = @project.user_stories.find(@new_parent_id)
        current_first_story = @user_story.parent_user_story.child_user_stories.first()
      end
      puts "###########current first story: " + current_first_story.inspect
      @user_story.stack_rank = current_first_story.nil? ? 0 : current_first_story.stack_rank - 10
    elsif @special_action == "sibling_change"
      # for the sibling change action, insert the story after (in stack rank order) the big brother
      @new_bigbro_id = params[:new_bigbro]
      @bigbro_user_story = @project.user_stories.find(@new_bigbro_id)

      if !@bigbro_user_story.parent_user_story.nil?
        all_siblings = @bigbro_user_story.parent_user_story.child_user_stories
      else
        all_siblings = @project.user_stories.where("parent_user_story_id is null")
      end

      counter = 0

      puts "************* about to reorder: " + all_siblings.count.to_s
      puts "bigbro: " + @bigbro_user_story.id.to_s
      puts "moved: " + @user_story.id.to_s

      all_siblings.each do |s|
        puts "--" + s.id.to_s + "-" + s.want_to + " - current rank: " + s.stack_rank.to_s
        if @user_story.id != s.id
          counter += 10
          if s.stack_rank != counter
            puts "----- CHANGING!" + s.id.to_s + " ------ " + counter.to_s
            s.stack_rank = counter
            s.save!
          end
        end
        if s.id == @bigbro_user_story.id
          counter += 10
          puts "--  MOVED " + @user_story.id.to_s + @user_story.want_to + " ------ " + counter.to_s
          @user_story.stack_rank = counter
        end
      end
      
      @user_story.parent_user_story = @bigbro_user_story.parent_user_story
    else
      # just an update from the story editor
      @user_story.want_to = params[:user_story][:want_to]
      @user_story.so_i_can = params[:user_story][:so_i_can]
      @user_story.is_estimate_final = false
      @user_story.actor = find_or_create_actor(params[:user_story][:actor_name])
      
      valid_notes = params[:user_story][:notes_attributes].select { |k, itm| !itm[:content].blank? }
      @user_story.notes_attributes = valid_notes
    end
   
    puts "+++++++inspect: " + @user_story.inspect

    @user_story.save!

    puts "++++++ saved"

    respond_to do |format|
      format.html { render :nothing => true }
      format.js 
    end
  end

  def create
    puts "++++++ in create"
    story_type = StoryType.where(:story_type_name => "Development").first
    puts "++++++ gonna save: " + params.inspect
   
    @user_story = @project.user_stories.new(params[:user_story])
    @user_story.priority = 5
    @user_story.story_type = story_type
    @user_story.is_fully_recorded = false
    @user_story.is_estimate_final = false
    @user_story.actor = find_or_create_actor(params[:user_story][:actor_name])
   
    puts @user_story.inspect

    @user_story.save!

    puts "++++++ saved"

    respond_to do |format|
      format.html { render :nothing => true }
      format.js 
    end
  end

  def find_or_create_actor(actor_name)
    actor = Actor.where(:actor_singular_name => actor_name, :project_id => @project.id).first
    if actor.nil?
      actor = @project.actors.create!(\
        :actor_singular_name => actor_name, \
        :actor_plural_name => actor_name.pluralize(2), \
        :use_an_instead_of_a => false)
    end
    puts "++++++ Actor:" + actor.inspect
    actor
  end

  def get_root_user_stories
    UserStory.where("parent_user_story_id is NULL and project_id = ?", @project.id)
  end

  def build_drawers
    retval = []

    retval.push({\
      :partial_name => "drawer_project_notes"\
      , :drawer_header => "Project Notes"\
      , :handle_text => "notes"\
    })

    retval.push({\
      :partial_name => "drawer_filters"\
      , :drawer_header => "Filters"\
      , :handle_text => "filters"\
    })

    retval.push({\
      :partial_name => "drawer_assign_to_buckets"\
      , :drawer_header => "Work Buckets"\
      , :handle_text => "buckets"\
    })

    retval.push({\
      :partial_name => "drawer_cheat_sheet"\
      , :drawer_header => "Cheat Sheet"\
      , :handle_text => "cheat"\
    })

    return retval
  end

  def get_actors
    if @project.nil?
      @project = Project.find(@user_story.project_id)
    end
    @project.actors
  end

end

app/helpers/user_stories_helper.rb
module UserStoriesHelper
end

app/views/user_stories/_drawer_assign_to_buckets.html.erb
where are my buckets???

app/views/user_stories/_drawer_cheat_sheet.html.erb
<h4>Create a story</h4>
<p>[ins] with a story selected</p>
<p>right click story &gt; insert after or child</p>
<h4>Edit a story</h4>
<p>[enter] with story selected</p>
<p>right click story &gt; edit</p>
<p>double click story</p>
<h4>Delete a story</h4>
<p>[del] key</p>
<p>right click story &gt; delete</p>
<h4>Change stack rank</h4>
<p>Drag story to 3px dropzone between stories</p>
<h4>Change parent</h4>
<p>Drag story into another story</p>

app/views/user_stories/_drawer_filters.html.erb
HERE I AM!!!  Filter me!!!!

app/views/user_stories/_drawer_project_notes.html.erb
<%= @project.notes.each do |note_f| %>
	<%= render "shared/notes_view" \
  		, :f => note_f \
  		, :tab_index => "3403" %>
<% end %>

app/views/user_stories/_editor_intree.html.erb
<!-- the tree editor allows editing of user stories by embedding the
control within tree that contains it.  When the user wants to edit
a story, this control 'wraps' the node of the story to edit and
injects it into the tree while its being edited-->
<div class="tree-editor" id="tree-editor">
  <%= form_for ([@project, @user_story]), :remote => true,\
    :html => { :'data-type' => 'html', :id => 'tree-editor-form'} do |f| %>
  <%= f.hidden_field :id, :id => "story-editor-id" %>
  <%= f.hidden_field :parent_user_story_id %>
  <%= f.hidden_field :stack_rank %>
  <div class="tree-editor-controls">
    <div class="tree-editor-controls-body">
      <div class="tree-editor-left">
        <label for="story-editor-actor">As a/an</label>
        <%= render "shared/tt_refined_list" \
          , :f => f \
          , :control_id => "story-editor-actor" \
          , :tab_index => "3400" \
          , :list_items => @all_actors %>
        
        <p class="label-field-pair">
            <%= f.label :want_to, "I want to" %>
            <%= f.text_area :want_to, :id => "story-editor-wantto", :tabindex => 3401 %>
        </p>
        <p class="label-field-pair">
            <%= f.label :so_i_can, "so I can" %>
            <%= f.text_area :so_i_can, :id => "story-editor-soican", :tabindex => 3402 %>
        </p>
      </div>
      <div class="tree-editor-right">
        this is where the right side should go
		<%= f.fields_for :notes do |note_f| %>
      		<%= render "shared/notes_view" \
          		, :f => note_f \
          		, :tab_index => "3403" %>
    	<% end %>
       </div>
    </div>
    <div class="tree-editor-controls tree-editor-commands">
      <a href="javascript:TTdeleteTreeNode($('#tree-editor').parents('.tree-node:first'));" class="btn-delete" tabindex="3482">Delete</a>
      <a href="javascript:TTeditorCancel();" class="btn-cancel" tabindex="3481">Cancel</a>
      <a href="javascript:TTeditorClose();" class="btn-save" tabindex="3480">Close</a>
      <a href="javascript:TTeditorDetails()" class="btn-details" tabindex="3483">Details</a>
    </div>
  </div>
<% end %>
</div>

app/views/user_stories/_user_story.html.erb
<li>
  <% user_story = @user_story if user_story.nil? %>
  <div id="tn-<%= user_story.id %>" draggable="true" class="tree-node" data-storyid="<%=user_story.id%>"
      , data-edit-url="<%= edit_project_user_story_path(@project, user_story)  if !user_story.id.nil? %>" >
    <div class="tree-node-nav TT-expanded">
        <div class="tree-node-command"></div>
        <div class="tree-node-fill"></div>
    </div>
    <div class="tree-node-function"><%= image_tag "loe-toobig.png"  %></div>
    <div class="tree-node-function"><%= image_tag "status-backlog.png"  %></div>
    <div class="tree-node-body">
      As a 
      <span class="story-actor"><%=user_story.actor.try(:actor_singular_name)%></span> 
      I want to 
      <span class="story-wantto"><%=user_story.want_to%></span> 
      <% if user_story.so_i_can.present? %>so I can <% end %>
      <span class="story-soican"><%=user_story.so_i_can%></span>
    </div>
    <% if !user_story.id.nil? %>
      <%= form_for user_story, \
        :url => project_user_story_path(@project,user_story)\
        , :method => :delete, :remote => true \
        , :html => { :'data-type' => 'html', :class => 'tn-form'} do  %>   
        <%# <%= link_to "Delete", "javascript:TThandleEditorDeleteClick();", data: {confirm: "Are you sure?"} %>
      <% end %>
    <% end %>
  </div>
  <%= render "shared/tt_tree_branch", :nodes => user_story.child_user_stories if user_story.child_user_stories.length > 0  %>
  <div class="tree-sibling-dropzone" data-storyid=<%= user_story.id %>>
    <div class="tree-node-nav"></div>
  </div>
</li>

app/views/user_stories/create.js.erb
var node = $('#tn-new');
var newNode = $('<%= j render(@user_story) %>');
updateTreeNode(node, newNode);

app/views/user_stories/destroy.js.erb
TThandleServerNodeDelete($('#tn-<%= @user_story_id.to_s %>'));

app/views/user_stories/edit.js.erb
// grab the root of the node we need to edit
var node = $('#tn-<%= @user_story.id %>');

// insert the editor into the node we are editing
node.append('<%= j render("editor_intree") %>');

// save a copy of the original node so we can use it if user wants to cancel the action
var backupCopy = node.children(".tree-node-body").clone(true,true);
backupCopy.removeClass("tree-node-body");
backupCopy.addClass("tree-node-body-backup");
backupCopy.hide();
node.children("#tree-editor").prepend(backupCopy);

// insert the body text into the editor so the editor can update in real time
node.children("#tree-editor").prepend(node.children(".tree-node-body"));

wireUpUserStoryEditor(node);

app/views/user_stories/index.html.erb
<% @page_title = "User Stories" %>
<%# <%= javascript_include_tag("TT_tree")%>
<%# <%= javascript_include_tag("TT_sliderChest")%>
<%# <%= javascript_include_tag("user_stories")%>

<section>
  <section class="main-body-parts-container main-body-section TTsliderCompanion full">
    <%= render "shared/tt_project_menu"  %>
    <h1>Work Breakdown</h1>
    <div id="userStoryTree" class="tree" data-new-url=<%= new_project_user_story_path(@project) %>>
      <!-- <p id="TTtreeDebugMessage"></p> -->
      <%= render "shared/tt_tree_branch", :nodes => @root_user_stories %>
    </div>
  </section>
  <aside id="sliderChest">
    <%= render "shared/tt_slider_chest"  %>
  </aside>
</section>

app/views/user_stories/new.js.erb
var jqNewNode = $("<%= j render(@user_story) %>");

// find the element that contains the node
var newTreeNode = jqNewNode.find(".tree-node");

<% if params[:parent].present? %>
  var jqParent = $("#tn-<%= j params[:parent] %>");
  TTensureNodeParenthood(jqParent);
  TTaddNewChild(jqParent, newTreeNode);
<% else %>
  var jqAfter = $("#tn-<%= j params[:after] %>").parentsUntil("ul");
  // insert the new node as a sibling after current node
  jqAfter.after(jqNewNode);
<% end %>

// wire up the events for the new node
TTwireUpTreeNodes(jqNewNode);

newTreeNode.attr("id", "tn-new");
 
// insert the editor into the node we are editing
newTreeNode.append('<%= j render("editor_intree") %>');

// insert the body text into the editor so the editor can update in real time
newTreeNode.children("#tree-editor").prepend(newTreeNode.children(".tree-node-body"));

wireUpUserStoryEditor(newTreeNode);
TTreindexTree(9000, newTreeNode);

app/views/user_stories/update.js.erb
// returned from server after successful update of a user story node

// get the tree node that contains the updated story
var node = $('#tn-<%= @user_story.id %>');

// generate the html of the updated story info
var newNode = $('<%= j render(@user_story) %>');

<% if @special_action == "parent_change" %>
  TTchangeTreeNodeParent(node, $("#tn-<%= @new_parent_id %>"));
<% end %>

<% if @special_action == "sibling_change" %>
  TTchangeTreeNodeSibling(node, $("#tn-<%= @new_bigbro_id %>"));
<% end %>

// call JS method to replace the node
updateTreeNode(node, newNode);

TTreindexTree(9000, newNode.find(".tree-node"));