config/routes.rb
Testtube::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :welcome, :only => [:index]
  resources :projects, :only => [:index, :show, :update, :destroy, :create] do
    member do
      post :save
    end

    resources :project_models, :only => [:index, :show], :shallow => true
    resources :project_users, :only => [:create, :update, :destroy], :shallow => true
    resources :story_types, :only => [:index, :show, :create, :edit, :update, :new, :destroy]
    resources :user_stories, :only => [:index, :show, :create, :edit, :update, :new, :destroy] do
      member do
        post :save
      end
    end

  end
  root :to => 'welcome#index'

end

app/controllers/story_types_controller.rb
class StoryTypesController < ApplicationController
  # GET /story_types
  # GET /story_types.json

  load_and_authorize_resource

  def index
    @story_types = [] if @story_types == nil

    #@story_types = StoryType.all

    @dummystory = StoryType.new


    #respond_to do |format|
    #  format.html # index.html.erb
    #  format.json { render json: @story_types }
    #end
  end

  # GET /story_types/1
  # GET /story_types/1.json
  def show
    @story_type = StoryType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story_type }
    end
  end

  # GET /story_types/new
  # GET /story_types/new.json
  def new
    @story_type = StoryType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story_type }
    end
  end

  # GET /story_types/1/edit
  def edit
    @story_type = StoryType.find(params[:id])
  end

  # POST /story_types
  # POST /story_types.json
  def create
    @story_type = StoryType.new(params[:story_type])

    respond_to do |format|
      if @story_type.save
        format.html { redirect_to @story_type, notice: 'Story type was successfully created.' }
        format.json { render json: @story_type, status: :created, location: @story_type }
      else
        format.html { render action: "new" }
        format.json { render json: @story_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /story_types/1
  # PUT /story_types/1.json
  def update
    @story_type = StoryType.find(params[:id])

    respond_to do |format|
      if @story_type.update_attributes(params[:story_type])
        format.html { redirect_to @story_type, notice: 'Story type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /story_types/1
  # DELETE /story_types/1.json
  def destroy
    @story_type = StoryType.find(params[:id])
    @story_type.destroy

    respond_to do |format|
      format.html { redirect_to story_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/story_types_helper.rb
module StoryTypesHelper
end

app/views/story_types/_form.html.erb
<%= form_for(@story_type) do |f| %>
  <% if @story_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story_type.errors.count, "error") %> prohibited this story_type from being saved:</h2>

      <ul>
      <% @story_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/story_types/edit.html.erb
<h1>Editing story_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @story_type %> |
<%= link_to 'Back', story_types_path %>

app/views/story_types/index.html.erb
<h1>Listing story_types</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @story_types.each do |story_type| %>
  <tr>
    <td><%= link_to 'Show', story_type %></td>
    <td><%= link_to 'Edit', edit_story_type_path(story_type) %></td>
    <td><%= link_to 'Destroy', story_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<!--%= link_to 'New Story type', new_story_type_path %>

app/views/story_types/new.html.erb
<h1>New Story time</h1>

<%= render 'form' %>

<%= link_to 'Back', story_types_path %>

app/views/story_types/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_story_type_path(@story_type) %> |
<%= link_to 'Back', story_types_path %>