config/routes.rb
Testtube::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :welcome, :only => [:index]
  resources :projects, :only => [:index, :show, :update, :destroy, :create] do
    member do
      post :save
    end

    resources :project_models, :only => [:index, :show], :shallow => true
    resources :project_users, :only => [:create, :update, :destroy], :shallow => true
    resources :story_types, :only => [:index, :show, :create, :edit, :update, :new, :destroy]
    resources :user_stories, :only => [:index, :show, :create, :edit, :update, :new, :destroy] do
      member do
        post :save
      end
    end

  end
  root :to => 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name, :is_public, :notes_attributes

  has_many :actors, :dependent => :destroy, :foreign_key => 'project_id'
  has_many :project_models, :dependent => :destroy, :foreign_key => 'project_id'
  has_many :story_types, :dependent => :destroy, :foreign_key => 'project_id'
  has_many :user_stories, :dependent => :destroy, :foreign_key => 'project_id'
  has_many :project_users, :dependent => :destroy, :foreign_key => 'project_id'
  has_many :users, :through => :project_users
  has_many :invitees, :through => :project_users

  has_many :notes, :as => :notable
  accepts_nested_attributes_for :notes

  validates :name, :uniqueness => {:message => "name must be unique"}
  
  # scope :mine, joins(:project_users).where('project_users.user_id = ?', (@user ||= User.new).id)
  scope :invited_to, (lambda do |email|
    joins("join project_users on project_users.project_id = projects.id \
          join invitees on project_users.invitee_id = invitees.id") \
          .where("invitees.email = ?", email)
     # where("exists (select 1 from project_users where projects.id = project_users.project_id and project_users.user_id = ?)", user_id)
   end)

  scope :view, (lambda do |user_id|
    user_id = (user_id.nil?) ? "-1" : user_id.to_s
     where("is_public = true or exists (select 1 from project_users where projects.id = project_users.project_id and project_users.user_id = ?)", user_id)
   end)

  scope :contribute, (lambda do |user_id|
    user_id = (user_id.nil?) ? "-1" : user_id.to_s
     where("exists (select 1 from project_users where projects.id = project_users.project_id and project_users.user_id = ? and (project_users.role = 'admin' or project_users.role = 'contribute'))", user_id)
   end)

  scope :admin, (lambda do |user_id|
    user_id = (user_id.nil?) ? "-1" : user_id.to_s
     where("(select 1 from project_users where projects.id = project_users.project_id and project_users.user_id = ? and project_users.role = 'admin')", user_id)
   end)

  def view?(user)
     is_public || project_users.any?{|project_user| project_user.user == user}
  end

  def contribute?(user)
    puts "********  is contributor??? " + user.inspect + "|||" + project_users.inspect
     project_users.any?{|project_user| project_user.user == user && (project_user.role == "admin" || project_user.role == "contrib")}
  end

  def admin?(user)
     project_users.any?{|project_user| project_user.user == user && project_user.role == "admin"}
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  def index
    @projects = [] if @projects == nil  #cancan leaves this nil if none were passed
    @dummy_project = Project.new
  end

  def destroy
    puts "***********removing: " + params.inspect 
    @project.destroy

    flash[:notice] = "Project has been purged"
    redirect_to projects_path
    
  end
  
  def show
    @new_user = User.new
    @dummy_pu = ProjectUser.new
  end

  def create
    puts "save me:  " +  params[:project][:id]

    puts "creating project"
    @project = Project.new(params[:project])
  
    @project.save!

    projectUser = @project.project_users.create( \
      :user_id => current_user.id, \
      :role => "admin")

    actorUser = @project.actors.create( \
      :actor_singular_name => "User", \
      :actor_plural_name => "Users", \
      :use_an_instead_of_a =>false)

    storyType = @project.story_types.create(:story_type_name => "Basic Task")

    firstStory = @project.user_stories.create( \
        :actor_id => actorUser.id, \
        :story_type_id => storyType.id, \
        :want_to => "start a project with an initial dummy story", \
        :so_i_can => "change it to be what I want it to be", \
        :priority => 1, \
        :is_fully_recorded => false, \
        :stack_rank => 0, \
        :is_estimate_final => false)

    respond_to do |format|
      format.html { render :nothing => true }
      format.js 
    end
    
  end

  def update
    puts "************ saving project" + params.inspect 
    # @project = Project.find(params[:id])
    puts "************ project:" + @project.inspect 
    # @project.notes_attributes = params[:user_story][:notes_attributes]

    @project.update_attributes!(params[:project])
    puts "************ done!" 
    render :nothing => true
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<div class="TTprojectCard">
  <h2>
    <%= link_to(project.name, project_path(project)) %>
  </h2>
  <p><%= project.description %></p>
    <p>
    <%= link_to "Stories", project_user_stories_path(project) %>
    <%= link_to "Story types", project_story_types_path(project) %>
    <%# <%= link_to "Models", project_project_models_path(project) %>
    </p>
  <% project.project_models.each do |model| %>
    <p><%= model.name %> (<%= model.description %>)</p>
  <% end %>
</div>

app/views/projects/_project_details_edit.html.erb
      <%= form_for @project, :remote => true do |f| %>
        <table class="form-fields">
          <tr>
            <td><%= f.label :name %></td>
            <td>
              <%= f.text_field :name, :class => "project-changer-delay" %>
              <img class="delay-status" src=""></img>
            </td>
          </tr>
          <tr>
            <td><%= f.label :description %></td>
            <td>
              <%= f.text_area :description, :class => "project-changer-delay" %>
              <img class="delay-status" src=""></img>
            </td>
          </tr>
          <tr>
            <td><%= f.label :is_public %></td>
            <td>
              <%= f.check_box :is_public, :class => "project-changer" %>
              <span>(<strong>anybody</strong> who finds, sees it)</span>
            </td>
          </tr>
        </table>
      <% end %>
      <%= form_for @project, :method => :delete do  %>   
        <%= submit_tag "Purge this project", confirm: "Are you sure you want to permanently remove this project?" %> 
      <% end %>

app/views/projects/_project_details_readonly.html.erb
      <table class="form-fields">
        <tr>
          <td>Name:</td>
          <td><%= @project.name %></td>
        </tr>
        <tr>
          <td>Description:</td>
          <td><%= @project.description %></td>
        </tr>
        <tr>
          <td>Is public?</td>
          <td>
            <%= @project.is_public ? "Public (anyone who finds it, sees it)" : "Private (need to be a member to see it)" %>
          </td>
        </tr>
      </table>

app/views/projects/create.js.erb
$('#projects').prepend('<%= j render(@project) %>');

app/views/projects/index.html.erb
<%= javascript_include_tag("projects")%>

<section class="main-body-parts-container">
<h1>Projects</h1>
<% if user_signed_in? %>
  <p><a href="#popup-edit-project?new" id="newProjectLink" class="TTpopupLink">Start a new project</a></p>
<% else %>
  <p><%= link_to "Login to start a new project", new_user_session_path %></p>
<% end %>
<div id="projects">
  <%= render @projects %>
</div>
</section>

<aside id="popupWrapper">
    <div id="popup-edit-project" class="TTpopup">
      <div id="popup-edit-project-body" class="TTpopupBody">
        <h1>Project Summary</h1>
        <%= form_for @dummy_project, \
          :url => projects_path(@dummy_project), \
          :html => { :'data-type' => 'js', :id => 'project-editor-form'} \
          do |f| %>
          <%= f.hidden_field :id, :id => "project-editor-projectid" %>
          <p class="label-field-pair">
            <%= f.label :name %>
            <%= f.text_field :name, :id => "project-editor-name", :tabindex => 5401 %>
          </p>
          <p class="label-field-pair">
            <%= f.label :description %>
            <%= f.text_area :description, :id => "project-editor-description", :tabindex => 5402 %>
          </p>
          <a href="javascript:$('#mask').hide();$('#popup-edit-project').hide();" class="btn-close" tabindex=5491>Cancel</a>
          <a href="javascript:$('#mask').hide();$('#popup-edit-project').hide();TTcreateProject($('#project-editor-form'));" class="btn-save" tabindex=5490>Save</a>
        <% end %>
      </div>
    </div>
</aside>

app/views/projects/show.html.erb
<%= javascript_include_tag("projects") %>

<section class="main-body-parts-container project-show">
    <%= render "shared/tt_project_menu" %>
<div class="parts">
  <div class="chunk">
    <h2>Info</h2>
    <% if can? :update, @project %>
      <%= render "project_details_edit" %>
    <% else %>
      <%= render "project_details_readonly" %>
    <% end %>
  </div>
  <div class="chunk">
    <h2>Status</h2>
    <p>Coming soon.  Include informaiton on the status of the project.  Number of stories, completeness, doneness, estimate, confidence, etc.</p>
  </div>
</div>
<div class="users">
  <div class="chunk">
    <h2>Project Users</h2>
    <% if can? :update, @project %>
      <%= render "project_users/project_users_edit" %>
    <% else %>
      <%= render "project_users/project_users_readonly" %>
    <% end %>
  </div>
  <aside class="hidden-closet">
    <%= form_for @dummy_pu, \
      :url => project_user_path(@project, @dummy_pu.id), \
      :remote => true, \
      :html => {:'data-type' => 'html', :id => 'change-project-user-form'} \
      do |f| %>
        <%= hidden_field_tag :project_id, @project.id %>
        <%= hidden_field_tag :project_user_id, @dummy_pu.id %>
        <%= hidden_field_tag :role, "set me please" %>
    <% end %>
  </aside>
</div>
</section>