config/routes.rb
Testtube::Application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :welcome, :only => [:index]
  resources :projects, :only => [:index, :show, :update, :destroy, :create] do
    member do
      post :save
    end

    resources :project_models, :only => [:index, :show], :shallow => true
    resources :project_users, :only => [:create, :update, :destroy], :shallow => true
    resources :story_types, :only => [:index, :show, :create, :edit, :update, :new, :destroy]
    resources :user_stories, :only => [:index, :show, :create, :edit, :update, :new, :destroy] do
      member do
        post :save
      end
    end

  end
  root :to => 'welcome#index'

end

app/models/project_user.rb
class ProjectUser < ActiveRecord::Base
   include ActionView::Helpers::TextHelper
  belongs_to :project
  belongs_to :user
  belongs_to :invitee
  attr_accessible :project_id, :role, :user_id, :invitee_id

  ROLE_VIEW = "view"
  ROLE_CONTRIBUTE = "contrib"
  ROLE_ADMINISTER = "admin"
  ROLES = {:view => "Viewer", :contrib => "Contributor", :admin => "Administrator"}

  validates_inclusion_of :role, :in => ROLES.map{|role| role[0].to_s }

  def email(current_user)
    retval = !user.nil? ? user.email : invitee.email

    # if the current user is not explicitly assigned to the project,
    # do not show the domain

    # if project.project_users. current_user.present?
    if !project.contribute?(current_user) && !project.admin?(current_user) 
      retval = truncate(retval, :length => 2, :separator => "@", :omission => "[HIDDEN]" )
    end

    return retval
  end
end

app/controllers/project_users_controller.rb
class ProjectUsersController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:destroy]

  def create
    puts "*********** ADDING USER TO PROJECT"
    user = User.find_by_email(params[:user][:email])
    
    @project = Project.find_by_id(params[:project_id])
    puts "got project: " + @project.inspect

    if user.nil?
      puts "*********** user did not exist, checking for invitee"
      invitee = Invitee.find_by_email(params[:user][:email])
      if invitee.nil?
        puts "*********** creating invitee"
        invitee = Invitee.new(:email => params[:user][:email])
        invitee.save
        puts "*********** created invitee"
      end
      @project_user = ProjectUser.find_by_project_id_and_invitee_id(@project.id, invitee.id)
    else
      puts "*********** user already existed"
      @project_user = ProjectUser.find_by_project_id_and_user_id(@project.id, user.id)
    end
    
    puts "got project user" + @project_user.inspect

    puts "roles???  " + ProjectUser::ROLES.map{|role| role[0].to_s}.inspect

    if @project_user.nil?
      puts "*********** CREATING PROJECT USER"
      if user.nil?
        @project_user = ProjectUser.new(:project_id => @project.id, :invitee_id => invitee.id, :role=> "view")
      else
        @project_user = ProjectUser.new(:project_id => @project.id, :user_id => user.id, :role=> "view")
      end
      @project_user.save!
    else
      puts "*********** USER ALREADY IN PROJECT"
    end
    
    respond_to do |format|
      format.html { render :nothing => true }
      format.js 
    end
  end

  def update
    puts "***********changing: " + params.inspect 
    @project = Project.find(params[:project_id])
    @project_user = @project.project_users.find(params[:id])

    puts "*********** setting role to " + params[:role]
    @project_user.role = params[:role]
    @project_user.save
    respond_to do |format|
      format.html { render :nothing => true }
      format.js 
    end
  end

  def destroy
    puts "***********removing: " + params.inspect 
    @project = Project.find(params[:project_id])
    @project_user = @project.project_users.find(params[:id])
    @project_user.destroy
    respond_to do |format|
      format.html { render :nothing => true }
      format.js 
    end
  end
end

app/helpers/project_users_helper.rb
module ProjectUsersHelper
end

app/views/project_users/_project_user.html.erb
        <tr id="project-user-<%= project_user.id %>" class="project-user">
          <td><%= project_user.email(current_user) %></td>
          <td>
            <%= select_tag "role_" + project_user.id.to_s, \
              options_for_select(ProjectUser::ROLES.map{|role| [ role[1], role[0] ]}, project_user.role), \
              :class => "role-selector", \
              :datapuid => project_user.id.to_s %>
          </td>
          <td>
            <a href="javascript:TTremoveProjectUser('<%= project_user_path(project_user, :project_id => @project.id) %>');">Remove</a>
          </td>
        </tr>

app/views/project_users/_project_users_edit.html.erb
    <%= form_for @new_user, \
      :url => project_project_users_path(@project.id), \
      :remote => true, \
      :html => {:'data-type' => 'html', :id => 'new-user-form'} \
      do |f| %>
      <div class="add-user-wrapper">
         <%= f.label :email %>
         <%= f.text_field :email, :class => "new-user", :id => "new-user-email", :placeholder => "Enter Email" %>
         
         <%= hidden_field_tag "project_id", @project.id %>
        <a id="new-user-link" href="#">Add</a>
      </div>
    <% end %>
    <table class="table project-users" id="project-user-table">
      <tr>
        <th class="user">User</th>
        <th class="role">Role</th>
        <th class="remove">Remove</th>
      </tr>
      <tbody id="project-user-table-body">
        <%= render @project.project_users %>
      </tbody>
      <%# <% @project.project_users.each do |pu| %>
      <%# <% end %>
    </table>

app/views/project_users/_project_users_readonly.html.erb
    <table class="table project-users">
      <tr>
        <th class="user">User</th>
        <th class="role">Role</th>
      </tr>
      <% @project.project_users.each do |pu| %>
        <tr>
          <td><%= pu.email(current_user) %></td>
          <td>
            <%= pu.role %>
          </td>
        </tr>
      <% end %>
    </table>

app/views/project_users/create.js.erb
$('#project-user-table-body').prepend('<%= j render(@project_user) %>');
var newRow = $("#project-user-<%= @project_user.id %>");
newRow.find("td:first").prepend("<img src='/assets/saved.png'/>");
newRow.find("td:first").find("img").fadeOut(2000);

newRow.find(".role-selector").change(function(e)
{
  TTchangeProjectRole($(this), e);
});

app/views/project_users/destroy.js.erb
$("#project-user-<%= @project_user.id %>").fadeOut(1000);

app/views/project_users/update.html.erb
<h1>ProjectUsers#update</h1>
<p>Find me in app/views/project_users/update.html.erb</p>

app/views/project_users/update.js.erb
var newRow = $("#project-user-<%= @project_user.id %>");

TTconfirmNodeSave(newRow.find("td:first"));